include:
  - project: 'synechron-code/cloud-devops/templates/pipeline-templates'
    ref: latest
    file:
      - /templates/jobs/.backstage-publish-docs.yaml
      - /templates/jobs/.python-dependency-check.yaml
      - /templates/jobs/.sast-check.yaml
      - /templates/jobs/.code-quality-check.yaml
      - /templates/jobs/.markdownlint.yaml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SEM_VER: $CI_COMMIT_TAG
  ACR_REGISTRY: "synecloudpracticeprodacr"
  AZURE_CLIENT_ID: $AZURE_PROD_CLIENT_ID
  AZURE_CLIENT_SECRET: $AZURE_PROD_CLIENT_SECRET
  AZURE_TENANT_ID: $ARM_TENANT_ID

stages:
  - test
  - document

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

get_token:
  tags:
    - icp
