site_name: nexuschat-pipelines
site_description: Nexus Chat v3 (Open WebUI) Pipelines is library of Synechron proprietary pipeline plugins that can be deployed into the nexus chat platform.
docs_dir: docs
nav:
  - Home: ../README.md
  - Contribution: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Security: SECURITY.md
plugins:
  - techdocs-core
